### ISSUE TITLE
Week 2 Completed App review

### ISSUE THREAD

**Issue by audip** [audip/MovieFlicks#13]
My app is complete, as per user stories for week 2, please review. /cc @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways.

### Some small comments:
- Good job using `UIScrollView` in `Details View Controller`. But there's a small issue. With some movies having long review, the scroll view isn't tall enough to show all the text like that:
  <img width="310" alt="screen shot 2016-02-07 at 9 21 40 am" src="https://cloud.githubusercontent.com/assets/7917093/12870540/53e88f3a-cd7c-11e5-84d3-d8505a292450.png">
- Good job customizing the navigation bar
- Well done implementing `popular tab` and `upcoming tab` with the cool icons :star:
- Great work implementing `search` feature :star: It's not a big deal but in case there is no result, you should show a label `No results found` to make your app more friendly :wink: A small issue is that I cannot hide the keyboard after searching.

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

**Comment by audip** [comment]
Do you have a suggestion for how to make the scroll view tall enough to show all text?
